In [1]:
# Loading + inspection of data before cleaning, filtering.

In [2]:
# Read_csv - loading with right options
import pandas as pd
df_metrics = pd.read_csv(
    "server_metrics.csv", 
    parse_dates = ["timestamp"],
    dtype = {"server_id" : "category"},
    na_values = ["N/A", "null", "-"]
)
print("shows exact columns names :", df_metrics.columns.tolist(), "\n")
# head() and tail() - first and last look
print("top 5 rows of df_metrics\n", df_metrics.head())
print("last 5 rows of df_metrics\n", df_metrics.tail())

shows exact columns names : ['timestamp', 'server_id', 'cpu_pct', 'memory_pct', 'response_ms', 'disk_pct', 'status']

top 5 rows of df_metrics
    timestamp server_id  cpu_pct  memory_pct  response_ms  disk_pct status
0 2026-01-01    srv-01     49.6        94.6        891.8      68.9     ok
1 2026-01-01    srv-02     32.3        33.9       1046.1      69.1     ok
2 2026-01-01    srv-03     21.6        96.0       1007.3      43.8     ok
3 2026-01-01    srv-04     34.5        50.7        653.5      58.1     ok
4 2026-01-01    srv-05     68.3        39.5        386.0      53.8     ok
last 5 rows of df_metrics
               timestamp server_id  cpu_pct  memory_pct  response_ms  disk_pct  \
520 2026-01-01 04:00:00    srv-01     22.5        73.3        411.5      63.1
521 2026-01-01 04:00:00    srv-02     39.7        57.9        918.9      44.9
522 2026-01-01 04:00:00    srv-03     42.9        41.0       1119.2      82.5
523 2026-01-01 04:00:00    srv-04     88.8        84.6        264.6      88.0
524 2026-01-01 04:00:00    srv-05     83.8        90.9        415.7      37.2

      status
520  warning
521       ok
522       ok
523       ok
524       ok

In [3]:
# head()  0 see the structure
df_metrics.head()

   timestamp server_id  cpu_pct  memory_pct  response_ms  disk_pct status
0 2026-01-01    srv-01     49.6        94.6        891.8      68.9     ok
1 2026-01-01    srv-02     32.3        33.9       1046.1      69.1     ok
2 2026-01-01    srv-03     21.6        96.0       1007.3      43.8     ok
3 2026-01-01    srv-04     34.5        50.7        653.5      58.1     ok
4 2026-01-01    srv-05     68.3        39.5        386.0      53.8     ok

In [4]:
# shape - know the size
print(df_metrics.shape)

(525, 7)

In [5]:
# info() - inspection command - dtype - nulls
df_metrics.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525 entries, 0 to 524
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    525 non-null    datetime64[ns]
 1   server_id    525 non-null    category
 2   cpu_pct      525 non-null    float64
 3   memory_pct   525 non-null    float64
 4   response_ms  525 non-null    float64
 5   disk_pct     525 non-null    float64
 6   status       525 non-null    object
dtypes: category(1), datetime64[ns](1), float64(4), object(1)
memory usage: 25.3+ KB

In [6]:
# describe() - gives stastical summary
df_metrics.describe()

,timestamp,cpu_pct,memory_pct,response_ms,disk_pct
count,525,525.000000,525.000000,525.000000,525.000000
mean,2026-01-02 23:14:17.142857216,60.033143,63.275048,624.382286,62.420000
min,2026-01-01 00:00:00,20.600000,30.200000,51.800000,30.300000
25%,2026-01-01 21:00:00,39.000000,45.000000,335.800000,46.700000
50%,2026-01-02 23:00:00,60.900000,64.200000,633.800000,62.400000
75%,2026-01-04 01:00:00,81.300000,80.100000,909.600000,78.700000
max,2026-01-05 03:00:00,98.600000,98.000000,1196.400000,94.800000
std,NaN,23.472532,20.001914,326.679761,18.859812

In [7]:
# isnull().sum() For percentage of nulls per column - null map
df_metrics.isnull().sum()

timestamp      0
server_id      0
cpu_pct        0
memory_pct     0
response_ms    0
disk_pct       0
status         0
dtype: int64

In [8]:
# value_counts() - category distribution
df_metrics["server_id"].value_counts()

server_id
srv-01    105
srv-02    105
srv-03    105
srv-04    105
srv-05    105
Name: count, dtype: int64

In [9]:
# statue distribution across fleet of servers
df_metrics["status"].value_counts(normalize=True).mul(100).round(1)
# NOrmalize gives percentages

status
ok          77.0
warning     17.3
critical     5.7
Name: proportion, dtype: float64

In [10]:
# nuniquye() - unique value counts
df_metrics.nunique()

timestamp      100
server_id        5
cpu_pct        371
memory_pct     356
response_ms    495
disk_pct       354
status           3
dtype: int64

In [11]:
# time range
df_metrics["timestamp"].agg(["min", "max"])

min   2026-01-01 00:00:00
max   2026-01-05 03:00:00
Name: timestamp, dtype: datetime64[ns]

In [12]:
# sample() - random cross section
df_metrics.sample(5) # 5 random rows
df_metrics.sample(frac=0.01) # 1 percent random sample

,timestamp,server_id,cpu_pct,memory_pct,response_ms,disk_pct,status
314,2026-01-03 14:00:00,srv-05,66.3,41.4,897.4,86.1,ok
521,2026-01-01 04:00:00,srv-02,39.7,57.9,918.9,44.9,ok
489,2026-01-05 01:00:00,srv-05,43.9,47.6,273.8,33.7,ok
324,2026-01-03 16:00:00,srv-05,56.8,34.1,696.6,92.2,ok
219,2026-01-02 19:00:00,srv-05,33.9,45.0,264.4,80.7,ok

In [13]:
# check column names - tolist()
df_metrics = pd.read_csv("server_metrics.csv")
print(df_metrics.columns.tolist())

['timestamp', 'server_id', 'cpu_pct', 'memory_pct', 'response_ms', 'disk_pct', 'status']

In [14]:
# Loading data, write to postgreSQL and read back required data through sql query in pandas. No CSV export needed.

import pandas as pd
from sqlalchemy import create_engine

df = pd.read_csv("server_metrics.csv")
df["timestamp"] = pd.to_datetime(df["timestamp"])

engine = create_engine("postgresql://postgres:postgres@localhost:5432/postgres")

df.to_sql("server_metrics", engine, if_exists="replace", index=False)
#if_exists="replace" drops and recreates the table every run 

df_output = pd.read_sql("""
    SELECT server_id, timestamp, cpu_pct, memory_pct, response_ms
    FROM server_metrics
    WHERE timestamp >= (
        SELECT MAX(timestamp) - INTERVAL '7 days'
        FROM server_metrics
    )
""", engine)
print(df_output.dtypes)
print(f"shape : {df_output.shape}")
print(f"Date range : {df_output['timestamp'].min()} to {df_output['timestamp'].max()}")
print(f"Row count : {len(df_output)}")
print(f"Max CPU : {df_output['cpu_pct'].max()}")
print(df_output.head())

server_id              object
timestamp      datetime64[ns]
cpu_pct               float64
memory_pct            float64
response_ms           float64
dtype: object
shape : (525, 5)
Date range : 2026-01-01 00:00:00 to 2026-01-05 03:00:00
Row count : 525
Max CPU : 98.6
  server_id  timestamp  cpu_pct  memory_pct  response_ms
0    srv-01 2026-01-01     49.6        94.6        891.8
1    srv-02 2026-01-01     32.3        33.9       1046.1
2    srv-03 2026-01-01     21.6        96.0       1007.3
3    srv-04 2026-01-01     34.5        50.7        653.5
4    srv-05 2026-01-01     68.3        39.5        386.0

In [15]:
# Task - Load server_metrics.csv correctly — with parse_dates, dtype for server_id as category, and na_values handling. Print info() and confirm server_id dtype is category.
df_metrics = pd.read_csv(
    "server_metrics.csv", 
    parse_dates =["timestamp"],
    dtype={"server_id" : "category"},
    na_values=["N/A", "null", "-"]
)

df_metrics.info()
print(df_metrics["server_id"].dtype)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525 entries, 0 to 524
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    525 non-null    datetime64[ns]
 1   server_id    525 non-null    category
 2   cpu_pct      525 non-null    float64
 3   memory_pct   525 non-null    float64
 4   response_ms  525 non-null    float64
 5   disk_pct     525 non-null    float64
 6   status       525 non-null    object
dtypes: category(1), datetime64[ns](1), float64(4), object(1)
memory usage: 25.3+ KB
category

In [16]:
# Task - Run the full triage protocol on df_metrics — all 8 commands. For each one write a one-line comment above it explaining what you're checking.
df_metrics.head()

   timestamp server_id  cpu_pct  memory_pct  response_ms  disk_pct status
0 2026-01-01    srv-01     49.6        94.6        891.8      68.9     ok
1 2026-01-01    srv-02     32.3        33.9       1046.1      69.1     ok
2 2026-01-01    srv-03     21.6        96.0       1007.3      43.8     ok
3 2026-01-01    srv-04     34.5        50.7        653.5      58.1     ok
4 2026-01-01    srv-05     68.3        39.5        386.0      53.8     ok

In [17]:
df_metrics.shape               # confirm expected row count
df_metrics.info()              # displays dtypes and null check
print(df_metrics.describe())          # gives fleet-wide statistical range column wise
# gives per server stastical breakdwon
df_metrics.isnull().sum() 
df_metrics.nunique()
df_metrics["timestamp"].agg(["min", "max"])
df_metrics["server_id"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 525 entries, 0 to 524
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   timestamp    525 non-null    datetime64[ns]
 1   server_id    525 non-null    category
 2   cpu_pct      525 non-null    float64
 3   memory_pct   525 non-null    float64
 4   response_ms  525 non-null    float64
 5   disk_pct     525 non-null    float64
 6   status       525 non-null    object
dtypes: category(1), datetime64[ns](1), float64(4), object(1)
memory usage: 25.3+ KB
                           timestamp     cpu_pct  memory_pct  response_ms  \
count                            525  525.000000  525.000000   525.000000
mean   2026-01-02 23:14:17.142857216   60.033143   63.275048   624.382286
min              2026-01-01 00:00:00   20.600000   30.200000    51.800000
25%              2026-01-01 21:00:00   39.000000   45.000000   335.800000
50%              2026-01-02 23:00:00   60.900000   64.200000   633.800000
75%              2026-01-04 01:00:00   81.300000   80.100000   909.600000
max              2026-01-05 03:00:00   98.600000   98.000000  1196.400000
std                              NaN   23.472532   20.001914   326.679761

         disk_pct
count  525.000000
mean    62.420000
min     30.300000
25%     46.700000
50%     62.400000
75%     78.700000
max     94.800000
std     18.859812

server_id
srv-01    105
srv-02    105
srv-03    105
srv-04    105
srv-05    105
Name: count, dtype: int64

In [18]:
# Task - From describe() output — which server metric has the highest variability (std)? Write your answer as a comment.
df_metrics.describe()

,timestamp,cpu_pct,memory_pct,response_ms,disk_pct
count,525,525.000000,525.000000,525.000000,525.000000
mean,2026-01-02 23:14:17.142857216,60.033143,63.275048,624.382286,62.420000
min,2026-01-01 00:00:00,20.600000,30.200000,51.800000,30.300000
25%,2026-01-01 21:00:00,39.000000,45.000000,335.800000,46.700000
50%,2026-01-02 23:00:00,60.900000,64.200000,633.800000,62.400000
75%,2026-01-04 01:00:00,81.300000,80.100000,909.600000,78.700000
max,2026-01-05 03:00:00,98.600000,98.000000,1196.400000,94.800000
std,NaN,23.472532,20.001914,326.679761,18.859812

In [19]:
#statistics per server
df_metrics.groupby("server_id", observed=True)[["cpu_pct", "memory_pct", "response_ms"]].describe()

          cpu_pct                                                      \
            count       mean        std   min   25%   50%   75%   max
server_id
srv-01      105.0  59.926667  24.365408  21.8  40.3  61.0  82.0  98.4
srv-02      105.0  59.931429  23.061858  20.7  39.0  57.5  81.2  98.2
srv-03      105.0  58.565714  23.097481  20.9  41.5  55.9  80.1  98.5
srv-04      105.0  59.409524  24.996359  20.6  34.5  61.0  82.8  98.6
srv-05      105.0  62.332381  22.005220  20.6  45.0  66.9  81.0  96.7

          memory_pct             ...             response_ms              \
               count       mean  ...   75%   max       count        mean
server_id                        ...
srv-01         105.0  62.511429  ...  80.6  96.2       105.0  643.574286
srv-02         105.0  64.458095  ...  81.3  98.0       105.0  633.023810
srv-03         105.0  65.094286  ...  82.6  97.3       105.0  622.768571
srv-04         105.0  62.209524  ...  78.5  97.6       105.0  632.403810
srv-05         105.0  62.101905  ...  82.4  97.0       105.0  590.140952


                  std   min    25%    50%    75%     max
server_id
srv-01     327.959456  51.8  406.0  642.0  909.6  1196.2
srv-02     309.103917  62.5  430.5  615.3  850.4  1196.1
srv-03     322.619677  70.7  333.7  619.4  891.2  1195.8
srv-04     312.745485  89.5  347.4  649.1  924.9  1159.8
srv-05     361.950961  56.4  251.1  583.0  916.4  1196.4

[5 rows x 24 columns]

In [20]:
# CPU breakdown per server
df_metrics.groupby("server_id", observed=True)["cpu_pct"].describe().round(2)

           count   mean    std   min   25%   50%   75%   max
server_id
srv-01     105.0  59.93  24.37  21.8  40.3  61.0  82.0  98.4
srv-02     105.0  59.93  23.06  20.7  39.0  57.5  81.2  98.2
srv-03     105.0  58.57  23.10  20.9  41.5  55.9  80.1  98.5
srv-04     105.0  59.41  25.00  20.6  34.5  61.0  82.8  98.6
srv-05     105.0  62.33  22.01  20.6  45.0  66.9  81.0  96.7

In [21]:
# Memory breakdown per server
df_metrics.groupby("server_id", observed=True)["memory_pct"].describe().round(2)

           count   mean    std   min   25%   50%   75%   max
server_id
srv-01     105.0  62.51  19.87  30.3  45.0  63.0  80.6  96.2
srv-02     105.0  64.46  19.98  30.8  45.6  66.9  81.3  98.0
srv-03     105.0  65.09  20.08  30.6  48.3  65.3  82.6  97.3
srv-04     105.0  62.21  18.96  32.4  47.1  59.4  78.5  97.6
srv-05     105.0  62.10  21.25  30.2  42.3  61.3  82.4  97.0

In [22]:
# Response time breakdown per server
df_metrics.groupby("server_id", observed=True)["response_ms"].describe().round(2)

           count    mean     std   min    25%    50%    75%     max
server_id
srv-01     105.0  643.57  327.96  51.8  406.0  642.0  909.6  1196.2
srv-02     105.0  633.02  309.10  62.5  430.5  615.3  850.4  1196.1
srv-03     105.0  622.77  322.62  70.7  333.7  619.4  891.2  1195.8
srv-04     105.0  632.40  312.75  89.5  347.4  649.1  924.9  1159.8
srv-05     105.0  590.14  361.95  56.4  251.1  583.0  916.4  1196.4

In [23]:
# Task : what percentage of rows in df_metrics have status == "critical". Use value_counts(normalize=True).
df_metrics.value_counts()

timestamp            server_id  cpu_pct  memory_pct  response_ms  disk_pct  status
2026-01-01 00:00:00  srv-01     49.6     94.6        891.8        68.9      ok          2
2026-01-01 02:00:00  srv-04     62.9     39.6        972.5        34.8      critical    2
2026-01-01 00:00:00  srv-02     32.3     33.9        1046.1       69.1      ok          2
2026-01-01 04:00:00  srv-05     83.8     90.9        415.7        37.2      ok          2
                     srv-04     88.8     84.6        264.6        88.0      ok          2
                                                                                       ..
2026-01-02 11:00:00  srv-03     34.1     74.4        323.9        36.5      ok          1
                     srv-02     38.3     75.7        72.7         36.8      warning     1
                     srv-01     32.3     78.7        807.8        31.8      ok          1
2026-01-02 10:00:00  srv-05     49.5     48.4        790.6        56.6      ok          1
2026-01-05 03:00:00  srv-05     58.9     69.3        1045.4       93.7      ok          1
Name: count, Length: 500, dtype: int64

In [24]:
df_metrics["status"].value_counts(normalize=True) * 100

status
ok          76.952381
warning     17.333333
critical     5.714286
Name: proportion, dtype: float64

In [25]:
critical_pct = df_metrics["status"].value_counts(normalize=True).get("critical", 0) * 100
print(critical_pct)

5.714285714285714

In [26]:
# Task: Load incidents.csv with correct parse_dates. Find:
# Total number of tickets
# Number of unresolved tickets
# Which category appears most
# Date range of tickets (created_at min and max)

import pandas as pd

# check column names

df_tickets = pd.read_csv("incidents.csv")
print(df_tickets.columns.tolist())

# Load data
df_tickets = pd.read_csv("incidents.csv", parse_dates=["created_at"])

# 1. Total number of tickets
total_tickets = len(df_tickets)

# 2. Number of unresolved tickets
unresolved_tickets = df_tickets["resolved_at"].isna().sum()

# 3. Most common category
most_common_category = df_tickets["category"].value_counts().idxmax()

# 4. Date range (min and max of created_at)
min_date = df_tickets["created_at"].min()
max_date = df_tickets["created_at"].max()

# Print results
print("Total tickets:", total_tickets)
print("Unresolved tickets:", unresolved_tickets)
print("Most common category:", most_common_category)
print("Date range:", min_date, "to", max_date)

['ticket_id', 'server_id', 'category', 'priority', 'created_at', 'resolved_at', 'resolved']
Total tickets: 213
Unresolved tickets: 88
Most common category: CPU High
Date range: 2026-01-01 18:00:00 to 2026-04-10 09:00:00

In [27]:
# Task -  Load app_logs.csv. Find the distribution of log_level values as percentages. Which level appears least?
df_logs = pd.read_csv("app_logs.csv")
print(df_logs)
# Distribution of log_level as percentages
log_dist = df_logs["log_level"].value_counts(normalize=True) * 100

print(log_dist)

# Least frequent log level
least_common = log_dist.idxmin()

print("Least frequent log level:", least_common)

               timestamp server_id log_level                       message  \
0    2026-01-01 07:26:00    srv-04      INFO      Connection timeout error
1    2026-01-01 03:46:00    srv-02      INFO           Database query slow
2    2026-01-08 16:29:00    srv-05     ERROR        CPU threshold exceeded
3    2026-01-04 12:34:00    srv-05   WARNING             Disk usage at 90%
4    2026-01-04 01:25:00    srv-04  CRITICAL         Authentication failed
..                   ...       ...       ...                           ...
310  2026-01-01 05:07:00    srv-01      INFO           Database query slow
311  2026-01-08 15:21:00    srv-04      INFO  Network packet loss detected
312  2026-01-08 13:18:00    srv-02     ERROR      Memory allocation failed
313  2026-01-01 05:36:00    srv-04      INFO           Database query slow
314  2026-01-03 04:09:00    srv-02  CRITICAL           Database query slow

    error_code
0         E004
1         E003
2         E001
3          NaN
4         E002
..         ...
310       E002
311       E004
312       E002
313       E001
314       E002

[315 rows x 5 columns]
log_level
INFO        47.301587
WARNING     24.761905
ERROR       14.920635
CRITICAL    13.015873
Name: proportion, dtype: float64
Least frequent log level: CRITICAL

In [28]:
# Task:  Across all three DataFrames — df_metrics, df_tickets, df_logs — print a summary table showing: DataFrame name, shape, null count total, and date range
import pandas as pd

summary = []

# Helper function
def get_summary(name, df, date_col=None):
    return {
        "DataFrame": name,
        "Shape": df.shape,
        "Total Nulls": df.isna().sum().sum(),
        "Start Date": df[date_col].min() if date_col else None,
        "End Date": df[date_col].max() if date_col else None
    }

# Add summaries (adjust date columns based on your data)
summary.append(get_summary("df_metrics", df_metrics, "timestamp"))
summary.append(get_summary("df_tickets", df_tickets, "created_at"))
summary.append(get_summary("df_logs", df_logs, "timestamp"))

# Convert to DataFrame
df_summary = pd.DataFrame(summary)

print(df_summary)

    DataFrame     Shape  Total Nulls           Start Date             End Date
0  df_metrics  (525, 7)            0  2026-01-01 00:00:00  2026-01-05 03:00:00
1  df_tickets  (213, 7)           88  2026-01-01 18:00:00  2026-04-10 09:00:00
2     df_logs  (315, 5)           51  2026-01-01 00:52:00  2026-01-10 23:49:00